name: assignment-autotest-test
on: [push]
jobs:
    unit-test:
        container: cuaesd/aesd-autotest:unit-test
        runs-on: ubuntu-22.04
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run: git submodule update --init --recursive
          - name: Run unit test
            run: ./unit-test.sh
     full-test:
         container: cuaesd/aesd-autotest:24-assignment3
         runs-on: ubuntu-22.04
         timeout-minutes: 120
         steps:
           - uses: actions/checkout@v2
           - name: Checkout submodules
             run : git submodule update --init --recursive
           - name: Run full test
             run: ./full-test.sh
